stages:
  - build
  - deploy

build site:
  stage: build
  script:
    - mvn clean
    - git pull origin master
    - mvn package  -Dmaven.test.skip=true
#   only:
#     - master

deploy site:
  stage: deploy
  script:
    - sudo systemctl restart socnet.service
    - mvn sonar:sonar -Dsonar.login=e5e266e93d8140c7ea8932a43bfd55d369b47efa
  only:
    - master
