build project:
  stage: build
  script:
    - sudo mvn clean
    - sudo mvn package  -Dmaven.test.skip=true
#   artifacts:
#     expire_in: 1 week
#     paths:
#       - distr
    

deploy site:
  stage: deploy
  script:
    - sudo systemctl restart socnet.service
    - mvn sonar:sonar -Dsonar.login=e5e266e93d8140c7ea8932a43bfd55d369b47efa
  only:
    - master
