stages:
    - test
    - package
    - deploy
    # - sonar

test:
  stage: test
  only:
    - master
    - merge_requests
  except:
    - tags

  before_script:
    - sudo rm -rf /home/gitlab-runner/builds
    - sudo systemctl stop socnet.service

  script:
    - echo 'test are running i swaer'
    - sudo mvn clean
  
package:
  stage: package
  only:
    - master
  except:
    - tags
  script:
    - sudo mvn package -Dmaven.test.skip=true
  artifacts:
    paths:
      - ./target/*.jar
      
deploy_to_server:
  stage: deploy
  only:
    - master
  except:
    - tags

  before_script:
    - sudo rm -rf /home/gitlab-runner/builds

  script:
    - sudo systemctl restart socnet.service
    
# update_sonar_report:
#   stage: sonar
#   only:
#     - master
#   except:
#     - tags
#   script:
#     - sudo mvn sonar:sonar -Dsonar.login=e5e266e93d8140c7ea8932a43bfd55d369b47efa
