image: maven:latest

build project:
  stage: build
  script:
    - mvn package 
    
deploy site:
  stage: deploy
  script:
    - sudo systemctl restart socnet.service
    - mvn sonar:sonar -Dsonar.login=e5e266e93d8140c7ea8932a43bfd55d369b47efa
  only:
    - master
