# before_script:
#   - echo "Before script section"
#   - echo "For example you might run an update here or install a build dependency"
#   - echo "Or perhaps you might print out some debugging details"

# after_script:
#   - echo "After script section"
#   - echo "For example you might do some cleanup here"

# build1:
#   stage: build
#   script:
#     - echo "Do your build here"

# test1:
#   stage: test
#   script:
#     - echo "Do a test here"
#     - echo "For example run a test suite"

# test2:
#   stage: test
#   script:
#     - echo "Do another parallel test here"
#     - echo "For example run a lint test"

# deploy1:
#   stage: deploy
#   script:
#     - echo "Do your deploy here"


# stages:
#     - test
#     - package
#     - deploy
#     - sonar

test:
  stage: test
  only:
    - master
    - merge_requests
  except:
    - tags
  script:
    - echo 'test are running i swear!!!!!!'
    - mvn clean
    - systemctl stop socnet.service
  
package:
  stage: package
  only:
    - master
  except:
    - tags
  script:
    - mvn package -Dmaven.test.skip=true
      
deploy_to_server:
  stage: deploy
  only:
    - master
  except:
    - tags
  script:
    - systemctl restart socnet.service
    
# update_sonar_report:
#   stage: sonar
#   only:
#     - master
#   except:
#     - tags
#   script:
#     - sudo mvn sonar:sonar -Dsonar.login=e5e266e93d8140c7ea8932a43bfd55d369b47efa
