stages:
    - test
    - build
    - package
    - deploy
    - sonar

test:
  stage: test
  only:
    - master
    - merge_requests
  except:
    - tags
  script:
    - mvn clean
  cache:
    paths:
      - ./target
      - ./.m2

build:
  stage: build
  only:
    - master
    - merge_requests
  except:
    - tags
  script:
    - mvn compile
  cache:
    paths:
      - ./target
      - ./.m2
      
package:
  stage: package
  only:
    - master
  except:
    - tags
  script:
    - mvn package -Dmaven.test.skip=true
  artifacts:
    paths:
      - target/*.jar
  cache:
    policy: pull
    paths:
      - ./target
      - ./.m2
      
deploy_to_server:
  stage: deploy
  only:
    - master
  except:
    - tags
  script:
    - systemctl restart socnet.service
    
update_sonar_report:
  stage: sonar
  only:
    - master
  except:
    - tags
  script:
    - mvn sonar:sonar -Dsonar.login=e5e266e93d8140c7ea8932a43bfd55d369b47efa
