stages:
    - build
    - test
    - deploy
    - sonar

build:
  stage: build
  only:
    - master
  except:
    - tags
  before_script:
    - echo "socnet is in stop state for now"
    - sudo systemctl stop socnet.service  
  script:
    - echo "Do your build here and there"
    - mvn clean compile -X -Dmaven.test.skip=true

module_testing:
  stage: test
  only:
    - master
  except:
    - tags
  script:
    - echo "Do a test here and there"
    - echo "For example run a test suite"

integrational_testing:
  stage: test
  only:
    - master
  except:
    - tags
  script:
    - echo "Do another parallel test here"
    - echo "For example run a lint test"

deploy:
  stage: deploy
  only:
    - master
  except:
    - tags
  script:
    - echo "Do your deploy here"
    - mvn package -Dmaven.test.skip=true
    - sudo systemctl start socnet.service

update_sonar_report:
  stage: sonar
  only:
    - master
  except:
    - tags
  script:
    - mvn clean package sonar:sonar -Dsonar.login=e5e266e93d8140c7ea8932a43bfd55d369b47efa
  after_script:
    - echo 'fire up socnet again!'
    - sudo systemctl restart socnet.service
