stages:
    - build
    - test
    - deploy
    - sonar

build:
  stage: build
  only:
    - master
  except:
    - tags
  script:
    - echo "Do your build here"
    - mvn clean package -X -Dmaven.test.skip=true

module_testing:
  stage: test
  only:
    - master
  except:
    - tags
  script:
    - echo "Do a test here"
    - echo "For example run a test suite"

integrational_testing:
  stage: test
  only:
    - master
  except:
    - tags
  script:
    - echo "Do another parallel test here"
    - echo "For example run a lint test"

deploy:
  stage: deploy
  only:
    - master
  except:
    - tags
  script:
    - echo "Do your deploy here"
    - sudo systemctl restart socnet.service

update_sonar_report:
  stage: sonar
  only:
    - master
  except:
    - tags
  script:
    - mvn sonar:sonar -Dsonar.login=e5e266e93d8140c7ea8932a43bfd55d369b47efa


# stages:
#     - test
#     - package
#     - deploy
#     - sonar

# test:
#   stage: test
#   only:
#     - master
#     - merge_requests
#   except:
#     - tags
#   script:
#     - echo 'test are running i swear!!!!!!'
#     - mvn clean
#     - systemctl stop socnet.service
  
# package:
#   stage: package
#   only:
#     - master
#   except:
#     - tags
#   script:
#     - mvn package -Dmaven.test.skip=true
      
# deploy_to_server:
#   stage: deploy
#   only:
#     - master
#   except:
#     - tags
#   script:
#     - systemctl restart socnet.service
    
# update_sonar_report:
#   stage: sonar
#   only:
#     - master
#   except:
#     - tags
#   script:
#     - sudo mvn sonar:sonar -Dsonar.login=e5e266e93d8140c7ea8932a43bfd55d369b47efa
